GET http://localhost:5000/product

###
GET http://localhost:5000/product/5


###
POST http://localhost:5000/product
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "title": "Product 4", 
    "price": "30000"
}

###
PATCH  http://localhost:5000/product/5
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "title": "Product 5", 
    "price": "500004"
}

###user
GET http://localhost:5000/user

###
POST http://localhost:5000/user
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "username" : "yusmira",
    "fullName" : "Yusmira Kartika",
    "password" : "Yusmira123",
    "address" : "Gianyar",
    "phone" : "082235265401",
    "positionId" : 2
}

###LOGON
POST http://localhost:5000/user/login
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "username" : "fajar",
    "password" : "Cxzdsaewq321"
}

###update user
PATCH http://localhost:5000/user/update/6
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "username" : "yusmira",
    "fullName" : "Yusmira Kartika",
    "password" : "Yusmira123",
    "address" : "Gianyar",
    "phone" : "082235265401",
    "salary" : 1500000
}


###batas login 


###position 
GET http://localhost:5000/position

###getbyid
GET http://localhost:5000/position/1


###creaet position
POST http://localhost:5000/position
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "name": "Manager"
}

###update
PUT  http://localhost:5000/position/1
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "name": "CEO ", 
    "isDelete": 0
}


###is_delete
PUT  http://localhost:5000/position/delete/1
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 


### POSITION



### ABSENT
###GET 
GET http://localhost:5000/absent


###
POST http://localhost:5000/absent
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "userId": 1,
    "status" : "1",
    "shift" : "morning",
    "description" : "hadir"
}

###
PATCH http://localhost:5000/absent/33
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "status" : "present"
}

###batasa absent

### LEAVE
GET http://localhost:5000/leave

### POST LEAVE
POST http://localhost:5000/leave
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "userId": 1,
    "fromDate": "2022-01-27",
    "untilDate": "2022-01-30",
    "description": "Saya ingin liburan sebentar 3 hr"
}

###update leve
PATCH http://localhost:5000/leave/8
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "status" : "approved"
}

### Salary
GET http://192.168.1.3:5000/salary

###update salary
PATCH http://localhost:5000/salary/1
Content-Type: application/json

# tolong perhatikan penulisan body "title": "produc rupiha", titik 2(:) tidak boleh ada spasi 
{
    "salary" : 700000
}
